apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    {{- include "cortexflow.labels" . | nindent 4 }}
    app: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - name: http
      port: {{ .Values.services.mlflow.port }}
      targetPort: {{ .Values.services.mlflow.port }}
      nodePort: {{ .Values.services.mlflow.nodePort }}
