apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortexflow-ui-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cortexflow-ui-frontend
  template:
    metadata:
      labels:
        app: cortexflow-ui-frontend
    spec:
      nodeSelector:
        role: head
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: cortexflow-ui-frontend
          image: ghcr.io/paksas/cortexflow-ui-frontend:main-ed325f84e95488923327e340fd7fae213fb6ee74
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
