apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortexflow-ui-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cortexflow-ui-frontend
  template:
    metadata:
      labels:
        app: cortexflow-ui-frontend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: cortexflow-ui-frontend
          image: ghcr.io/paksas/cortexflow-ui-frontend:main-83240057512053f2769e3ff0ff65652e930c9c9d
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
