apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortexflow-ui-backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cortexflow-ui-backend
  template:
    metadata:
      labels:
        app: cortexflow-ui-backend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceAccountName: cortexflow-ui-backend
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: cortexflow-ui-backend
          image: ghcr.io/paksas/cortexflow-ui-backend:main-85d90d56a962c3fd8cc08925452209e7769a8415
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.mlflow.svc.cluster.local:5000
            - name: RAY_JOB_SERVER_URI
              value: http://ray-head.ray.svc.cluster.local:8265
            - name: AWS_S3_ENDPOINT_URL
              value: http://minio.minio.svc.cluster.local:9000
          envFrom:
            - secretRef:
                name: aws-creds
            - secretRef:
                name: cortexflow-ui-public-urls
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
