apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service.yaml
  - secrets.yaml
  - role-based-access-control.yaml
