apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cortexflow-ui-public-urls
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cortexflow-ui-public-urls
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        PUBLIC_MLFLOW_URL: "http://{{ .CONTROL_PLANE_TAILSCALE_IP }}:30500"
        PUBLIC_RAY_DASHBOARD_URL: "http://{{ .CONTROL_PLANE_TAILSCALE_IP }}:30265"
        PUBLIC_MINIO_CONSOLE_URL: "http://{{ .CONTROL_PLANE_TAILSCALE_IP }}:30901"
  data:
    - secretKey: CONTROL_PLANE_TAILSCALE_IP
      remoteRef:
        key: robolab/infra/CONTROL_PLANE_TAILSCALE_IP
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
