apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/robodatalab/robolab-infra.git
    targetRevision: main
    path: k8s/workloads/mlflow-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
