apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: mlflow
    targetRevision: 2.0.0
    helm:
      values: |
        tracking:
          service:
            type: NodePort
            nodePorts:
              http: 30500
          auth:
            enabled: false
          resourcesPreset: "none"
        minio:
          enabled: false
        externalS3:
          host: minio.minio.svc.cluster.local
          port: 9000
          protocol: http
          accessKeyID: admin
          accessKeySecret: adminadmin
          bucket: mlflow-artifacts
        postgresql:
          auth:
            username: mlflow
            password: mlflow
            database: mlflow
          primary:
            resourcesPreset: "none"
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
