apiVersion: batch/v1
kind: Job
metadata:
  name: cortexflow-integration-tests
  namespace: cortexflow
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
  labels:
    app.kubernetes.io/part-of: cortexflow
    app.kubernetes.io/component: integration-tests
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        role: head
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: tests
          image: ghcr.io/robodatalab/cortexflow-integration:111d788687963ac27e06100bda7e95870020754a
          volumeMounts:
            - name: test-results
              mountPath: /tmp
            - name: aws-creds
              mountPath: /root/.aws
              readOnly: true
      volumes:
        - name: test-results
          emptyDir: {}
        - name: aws-creds
          secret:
            secretName: aws-creds
            items:
              - key: credentials
                path: credentials
