apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.2.0
    helm:
      values: |
        grafana:
          adminPassword: admin
          service:
            type: NodePort
            nodePort: 30300
          grafana.ini:
            auth.anonymous:
              enabled: true
              org_role: Viewer
            security:
              allow_embedding: true
          nodeSelector:
            role: head
        prometheus:
          service:
            type: NodePort
            nodePort: 30090
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            retention: 30d
            nodeSelector:
              role: head
        alertmanager:
          alertmanagerSpec:
            nodeSelector:
              role: head
        prometheusOperator:
          nodeSelector:
            role: head
        kube-state-metrics:
          nodeSelector:
            role: head
        prometheus-node-exporter:
          nodeSelector:
            role: head
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
