aws_region  = "us-east-1"
domain_name = "robodatalab.com"
github_repo = "paksas/robolabwebsite"
environment = "production"

admin_email        = "ptrochim@proton.me"
from_email         = "noreply@robodatalab.com"
db_name            = "robolab_auth"
db_username        = "robolab_auth"
api_gateway_domain = "r9ibn992l1.execute-api.us-east-1.amazonaws.com"
