apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-bootstrap-creds
            key: AWS_ACCESS_KEY_ID
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-bootstrap-creds
            key: AWS_SECRET_ACCESS_KEY
            namespace: external-secrets
