apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ray-head
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "cortexflow.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ray-head
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
