apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.1
    releaseName: arc-runners
    namespace: arc-runners
    includeCRDs: false
    valuesMerge: replace
    valuesInline:
      runnerScaleSetName: arc-runners
      githubConfigUrl: https://github.com/robodatalab
      githubConfigSecret: arc-github-app
      controllerServiceAccount:
        namespace: arc-systems
        name: arc-controller-gha-rs-controller
      minRunners: 0
      maxRunners: 8
      containerMode:
        type: dind
      template:
        spec:
          nodeSelector:
            role: head
          imagePullSecrets:
            - name: ghcr-pull
          containers:
            - name: runner
              image: ghcr.io/robodatalab/arc-runner:main-6a02c79b8e38b9f267d39c28824479849c486e77
              command: ["/home/runner/run.sh"]
patches:
  - target:
      group: actions.github.com
      version: v1alpha1
      kind: AutoscalingRunnerSet
      name: arc-runners
    patch: |-
      - op: add
        path: /spec/template/spec/initContainers/1/args/-
        value: --mtu=1230
