apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: cortexgrid_ui
    releaseName: cortexgrid-ui
    namespace: cortexgrid
    valuesInline:
      images:
        backend: ghcr.io/robodatalab/cortexgrid-ui-backend:1734d56671a1bf1f26b7110d07337049874b288d
        frontend: ghcr.io/robodatalab/cortexgrid-ui-frontend:da082c594fc7b194d24261744b4b3bdb6d59b4ca
