apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: cortexgrid_ui
    releaseName: cortexgrid-ui
    namespace: cortexgrid
    valuesInline:
      images:
        backend: ghcr.io/robodatalab/cortexgrid-ui-backend:5a35602b457d99d66b5ee154f801af70260c9c90
        frontend: ghcr.io/robodatalab/cortexgrid-ui-frontend:5a35602b457d99d66b5ee154f801af70260c9c90
