apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - worker-daemonset.yaml
  - service.yaml
  - metrics.yaml
  - secrets.yaml
  - dashboard-ray-jobs.yaml
  - dashboard-ray-overview.yaml
  - dashboard-ray-default-upstream.yaml
  - dashboard-ray-data-upstream.yaml
  - dashboard-ray-serve-upstream.yaml
  - dashboard-ray-serve-deployment-upstream.yaml
