apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- worker-daemonset.yaml
- service.yaml
- metrics.yaml
- secrets.yaml
- dashboard-ray-jobs.yaml
- dashboard-ray-overview.yaml
- dashboard-ray-default-upstream.yaml
- dashboard-ray-data-upstream.yaml
- dashboard-ray-serve-upstream.yaml
- dashboard-ray-serve-deployment-upstream.yaml
images:
- name: ghcr.io/paksas/ray-head
  newName: ghcr.io/paksas/ray-head
  newTag: main-c9396f54e7ba4bf96a388a93346d7e9add6035e5
