apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.16.0
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            type: s3
            bucketNames:
              chunks: robolab-data
              ruler: robolab-data
              admin: robolab-data
            s3:
              region: eu-west-2
              s3ForcePathStyle: false
          limits_config:
            retention_period: 168h
          compactor:
            retention_enabled: true
            delete_request_store: s3
        singleBinary:
          replicas: 1
          nodeSelector:
            role: head
          extraEnv:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: AWS_SECRET_ACCESS_KEY
          persistence:
            enabled: false
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        gateway:
          enabled: false
        test:
          enabled: false
        lokiCanary:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
