#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Pull secrets from AWS Secrets Manager and generate .env
# =============================================================================
# Prerequisites: aws CLI configured with credentials that can read
# robolab/infra/* secrets (the robolab-dgx IAM user or your personal profile).
#
# Usage:
#   bash scripts/pull-secrets.sh                # writes .env
#   bash scripts/pull-secrets.sh --print        # prints to stdout (no file write)
#   AWS_PROFILE=robolab bash scripts/pull-secrets.sh   # use a specific profile

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ ! -f "$REPO_ROOT/docker-compose.yml" ]]; then
    echo "Error: Run from the local-dgx-training directory." >&2
    echo "  cd terraform/platform/local-dgx-training && bash scripts/pull-secrets.sh" >&2
    exit 1
fi

REGION="${AWS_REGION:-us-east-1}"
PRINT_ONLY=false
if [[ "${1:-}" == "--print" ]]; then
    PRINT_ONLY=true
fi

# --- Check aws CLI ---
if ! command -v aws &>/dev/null; then
    echo "Error: aws CLI is not installed." >&2
    echo "  Install: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html" >&2
    exit 1
fi

# --- Helper: fetch a secret value ---
get_secret() {
    local secret_id="$1"
    aws secretsmanager get-secret-value \
        --secret-id "$secret_id" \
        --region "$REGION" \
        --query 'SecretString' \
        --output text 2>/dev/null
}

echo "Pulling secrets from AWS Secrets Manager (region: ${REGION})..." >&2

# --- Fetch all secrets ---
DGX_TAILSCALE_IP=$(get_secret "robolab/infra/dgx-tailscale-ip") || { echo "Error: Failed to fetch dgx-tailscale-ip" >&2; exit 1; }
POSTGRES_PASSWORD=$(get_secret "robolab/infra/mlflow-postgres-password") || { echo "Error: Failed to fetch mlflow-postgres-password" >&2; exit 1; }
MINIO_ROOT_PASSWORD=$(get_secret "robolab/infra/minio-root-password") || { echo "Error: Failed to fetch minio-root-password" >&2; exit 1; }
GRAFANA_ADMIN_PASSWORD=$(get_secret "robolab/infra/grafana-admin-password") || { echo "Error: Failed to fetch grafana-admin-password" >&2; exit 1; }

echo "All secrets fetched successfully." >&2

# --- Generate .env content ---
ENV_CONTENT="# =============================================================================
# Generated by scripts/pull-secrets.sh — do not edit manually
# Regenerate with: bash scripts/pull-secrets.sh
# =============================================================================

# --- Network ---
DGX_TAILSCALE_IP=${DGX_TAILSCALE_IP}

# --- PostgreSQL (MLflow backend store) ---
POSTGRES_USER=mlflow
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=mlflow

# --- MinIO ---
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# --- Storage (MinIO locally, S3 on AWS) ---
ARTIFACT_STORE_ENDPOINT=http://minio:9000
ARTIFACT_STORE_BUCKET=mlflow-artifacts
ARTIFACT_STORE_ACCESS_KEY=minioadmin
ARTIFACT_STORE_SECRET_KEY=${MINIO_ROOT_PASSWORD}

# --- MLflow ---
MLFLOW_TRACKING_URI=http://\${DGX_TAILSCALE_IP}:5000
MLFLOW_ARTIFACT_ROOT=s3://mlflow-artifacts/

# --- Grafana ---
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

# --- Ray GCS (Redis) ---
RAY_REDIS_ADDRESS=redis:6379
"

if [[ "$PRINT_ONLY" == "true" ]]; then
    echo "$ENV_CONTENT"
else
    echo "$ENV_CONTENT" > "$REPO_ROOT/.env"
    echo "Wrote $REPO_ROOT/.env" >&2
fi
