apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.14.1
    helm:
      releaseName: arc-runners
      values: |
        runnerScaleSetName: arc-runners
        githubConfigUrl: https://github.com/robodatalab
        githubConfigSecret: arc-github-app
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-controller-gha-rs-controller
        minRunners: 0
        maxRunners: 3
        containerMode:
          type: dind
        template:
          spec:
            nodeSelector:
              role: head
            containers:
              - name: dind
                args:
                  - dockerd
                  - --host=unix:///var/run/docker.sock
                  - --group=$(DOCKER_GROUP_GID)
                  - --mtu=1230
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
