"""Backend configuration constants."""
from __future__ import annotations

EXPERIMENTS_STREAM_POLL_INTERVAL_SEC = 10
RUN_JOBS_STREAM_POLL_INTERVAL_SEC = 10
RUN_DASHBOARD_STREAM_POLL_INTERVAL_SEC = 10
JOB_STREAM_POLL_INTERVAL_SEC = 10
