"""One-off: copy hand-provided secrets from AWS Secrets Manager into a .env.head file.

Before the head secrets server existed, every secret lived in AWS Secrets
Manager under robolab/infra/*. This reads them with your local AWS credentials
and writes the ones head setup can't generate to a dotenv file, so they can be
merged into .env.head. Keys head setup generates or reads from terraform, and
keys nothing uses any more, are skipped.

Usage:
    uv run python scripts/export_sm_to_env.py [--out .env.head.migrated]

Delete this script once every cluster has moved to the head secrets server.
"""

import argparse
from pathlib import Path

import boto3  # type: ignore
from dotenv import set_key


_PREFIX = "robolab/infra/"
_REGION = "eu-west-2"

# Generated by head setup (or TerraformOutputs on AWS); a copy would be stale.
_GENERATED = {
    "K3S_NODE_TOKEN",
    "CONTROL_PLANE_TAILSCALE_IP",
    "MLFLOW_TRACKING_URI",
    "RAY_JOB_SERVER_URI",
    "RAY_SERVE_URI",
    "MLFLOW_BACKEND_STORE_URI",
    "NOTES_DB_URI",
    "S3_ACCESS_KEY_ID",
    "S3_SECRET_ACCESS_KEY",
    "S3_REGION",
    "S3_ENDPOINT_URL",
    "S3_BUCKET_NAME",
}
# Only existed to reach Secrets Manager or were never read.
_OBSOLETE = {
    "SM_ACCESS_KEY_ID",
    "SM_SECRET_ACCESS_KEY",
    "SM_REGION",
    "ROUTE53_REGION",
    "AWS_ROLE_ARN",
}


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--out", type=Path, default=Path(".env.head.migrated"))
    args = p.parse_args()

    client = boto3.client("secretsmanager", region_name=_REGION)
    names = [
        entry["Name"]
        for page in client.get_paginator("list_secrets").paginate(
            Filters=[{"Key": "name", "Values": [_PREFIX]}]
        )
        for entry in page["SecretList"]
        if entry["Name"].startswith(_PREFIX) and entry.get("DeletedDate") is None
    ]

    args.out.touch(mode=0o600)
    skipped = []
    for name in sorted(names):
        key = name[len(_PREFIX) :]
        if key in _GENERATED or key in _OBSOLETE or key.startswith("it-"):
            skipped.append(key)
            continue
        value = client.get_secret_value(SecretId=name)["SecretString"]
        set_key(args.out, key, value, quote_mode="always")
        print(f"exported {key}")

    print(f"skipped (generated by head setup or obsolete): {', '.join(skipped) or '(none)'}")
    print(f"Wrote {args.out}. Merge it into .env.head, then run head setup.")


if __name__ == "__main__":
    main()
