apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-config
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mlflow-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        MLFLOW_BACKEND_STORE_URI: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .db }}"
  data:
    - secretKey: username
      remoteRef:
        key: robolab/infra/RDS_USERNAME
    - secretKey: password
      remoteRef:
        key: robolab/infra/RDS_PASSWORD
    - secretKey: host
      remoteRef:
        key: robolab/infra/RDS_HOST
    - secretKey: port
      remoteRef:
        key: robolab/infra/RDS_PORT
    - secretKey: db
      remoteRef:
        key: robolab/infra/RDS_DB_NAME
