apiVersion: v1
kind: Service
metadata:
  name: mlflow
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
