apiVersion: batch/v1
kind: Job
metadata:
  name: cortexflow-ui-integration-tests
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
  labels:
    {{- include "cortexflow_ui.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: tests
          image: {{ .Values.images.integration }}
          volumeMounts:
            - name: test-results
              mountPath: /tmp
      volumes:
        - name: test-results
          emptyDir: {}
