apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: cortexflow_ui
    releaseName: cortexflow-ui
    namespace: cortexflow
    valuesInline:
      images:
        backend: ghcr.io/robodatalab/cortexflow-ui-backend:1508769c4422119c5d2682664cc1e156ce54491f
        frontend: ghcr.io/robodatalab/cortexflow-ui-frontend:04228357687bb32056a323b63567d247d5182e53
