apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: cortexflow_ui
    releaseName: cortexflow-ui
    namespace: cortexflow
    valuesInline:
      images:
        backend: ghcr.io/robodatalab/cortexflow-ui-backend:8de836cc78ef2ac2d79f234dd3d0816fed45d72a
        frontend: ghcr.io/robodatalab/cortexflow-ui-frontend:68e3af172b9cc3cbd4be011ced6e34145a93f4ba
