apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://ray-project.github.io/kuberay-helm
    chart: kuberay-operator
    targetRevision: 1.2.2
  destination:
    server: https://kubernetes.default.svc
    namespace: kuberay
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
