apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/image-list: ray-head=ghcr.io/paksas/ray-head
    argocd-image-updater.argoproj.io/ray-head.update-strategy: newest-build
    argocd-image-updater.argoproj.io/ray-head.allow-tags: regexp:^main-[0-9a-f]{40}$
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paksas/robolab-infra.git
    targetRevision: main
    path: k8s/workloads/ray
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: ray
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
