apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow
  labels:
    {{- include "cortexgrid.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.services.mlflow.ingressHost }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.services.mlflow.ingressHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlflow
                port:
                  number: {{ .Values.services.mlflow.port }}
