apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - loki.yaml
patches:
  - target:
      kind: Application
      name: secrets
    patch: |
      - op: replace
        path: /spec/source/path
        value: k8s/argo_deployments/aws/secrets
