apiVersion: v1
kind: Service
metadata:
  name: cortexflow-ui-frontend
  labels:
    {{- include "cortexflow_ui.labels" . | nindent 4 }}
    app: cortexflow-ui-frontend
spec:
  type: NodePort
  selector:
    app: cortexflow-ui-frontend
  ports:
    - name: http
      port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.services.frontend.port }}
      nodePort: {{ .Values.services.frontend.nodePort }}
