name: on_post_merge_cortexflow

on:
    push:
        branches: [main]
        paths:
            - "cortexflow/**"
            - "tests/unit/cortexflow/**"
            - "tests/integration/cortexflow/**"
            - "k8s/docker/integration_tests/cortexflow/**"
            - "jobs_control_plane/**"
            - "k8s/docker/jobs_control_plane/**"
            - "tests/unit/jobs_control_plane/**"
            - "k8s/docker/mlflow/**"
            - "k8s/docker/ray/**"

concurrency:
    group: cortexflow-integration
    cancel-in-progress: false

jobs:
    wait_for_cortexflow_deployment:
        runs-on: arc-runners
        steps:
            - run: argocd app sync cortexflow && argocd app wait cortexflow --health --sync --timeout 600

    test_cortexflow_integration:
        needs: wait_for_cortexflow_deployment
        runs-on: arc-runners
        steps:
            - run: kubectl apply -f k8s/workloads/cortexflow_integration_tests/job.yaml
            - run: kubectl wait --for=condition=complete job/cortexflow-integration --timeout=15m
